
services:
    web:
        build: './docker-build/php/'
        ports:
            - "443:443"
        volumes:
            - .:/var/www/api-classic-motors/
        links:
            - db:db
    db:
        build: './docker-build/mysql/'
        volumes:
            - ~/.docker/mysql:/var/lib/mysql
        ports:
            - "3307:3307"
        environment:
            - MYSQL_ROOT_PASSWORD=thisisapassworddamned
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8083:80"
        links:
            - db:db
   
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
