<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPM4gu2C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPM4gu2C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPM4gu2C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPM4gu2C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPM4gu2C\App_KernelDevDebugContainer([
    'container.build_hash' => 'PM4gu2C',
    'container.build_id' => '93793ecf',
    'container.build_time' => 1743680951,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPM4gu2C');
